name: Build GeoSite

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone external domains repository
        run: |
          git clone https://github.com/v2fly/domain-list-community.git external-domains

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Generate GeoSite
        run: go run main.go -data ./external-domains/data -nash ./nash -config config.json

      - name: Keepalive Workflow
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git checkout main
          
          git commit --allow-empty -m "Chore: Keepalive cron subscription $(date +'%Y-%m-%d')"
          git push origin main

      - name: Force Push to release-geosite branch
        run: |
          git checkout --orphan release-geosite
          git rm -rf . --quiet || true
          
          git add geositebr.dat
          git commit -m "Update geositebr.dat - $(date +'%Y-%m-%d')"
          git push -f -u origin release-geosite

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: geositebr.dat
          tag: "latest"
          overwrite: true
          release_name: "Daily Routing Data"
